name: Build and push to GHCR

on:
  workflow_call:
    inputs:
      image_name:
        description: "Name of the image to build"
        required: true
        type: string
      context:
        description: "Directory where the image is built, defaults to repository root"
        required: false
        default: "./"
        type: string

jobs:
  skip_ci:
    runs-on: ubuntu-latest
    outputs:
      canSkip: ${{ steps.check.outputs.canSkip }}
    steps:
      - id: check
        uses: Legorooj/skip-ci@main

  build_and_push_docker_to_ghcr:
    needs: skip_ci
    if: ${{ needs.skip_ci.outputs.canSkip != 'true' }}
    runs-on: ubuntu-latest
    permissions:
      packages: write
      security-events: write
      actions: read
      contents: read

    steps:
      - name: Checkout Code
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6

      - name: Log into registry
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta Service Name for ghcr.io
        id: docker_meta_img
        uses: docker/metadata-action@c299e40c65443455700f0fdfc63efafe5b349051 # v5
        with:
          context: git
          images: ghcr.io/${{ github.repository_owner }}/${{ inputs.image_name }}
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=sha,prefix=sha-
            type=ref,event=branch,suffix=-latest

      - name: Create lowercase image ref
        id: lower-repo
        env:
          repo_ref: ghcr.io/${{ github.repository_owner }}/${{ inputs.image_name }}:${{ env.DOCKER_METADATA_OUTPUT_VERSION }}
          image_ref: ghcr.io/${{ github.repository_owner }}/${{ inputs.image_name }}
        run: |
          echo "repository=${repo_ref@L}" >> $GITHUB_OUTPUT
          echo "image=${image_ref@L}" >> $GITHUB_OUTPUT

      - name: Build and push ${{ github.repository }}
        id: docker_build_push
        uses: docker/build-push-action@v6
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: ${{ inputs.context }}
          platforms: linux/amd64
          push: true
          tags: ${{ steps.docker_meta_img.outputs.tags }}
          labels: ${{ steps.docker_meta_img.outputs.labels }}

      - name: Export Docker image as tar
        run: |
          mkdir -p ${{ github.workspace }}/clamavscan/container_fs
          chmod -R 777 ${{ github.workspace }}/clamavscan
          docker create --name temp_scan_container ${{ steps.lower-repo.outputs.image }}:latest
          docker export temp_scan_container -o ${{ github.workspace }}/clamavscan/container_fs.tar
          tar -xf ${{ github.workspace }}/clamavscan/container_fs.tar -C ${{ github.workspace }}/clamavscan/container_fs
          docker rm temp_scan_container
          rm -rf ${{ github.workspace }}/clamavscan/container_fs.tar

      - name: Run ClamAV scan
        run: |
          docker run --rm -v ${{ github.workspace }}/clamavscan:/scan clamav/clamav:latest freshclam --datadir=/scan
          docker run --rm -v ${{ github.workspace }}/clamavscan:/scan clamav/clamav:latest clamscan /scan/container_fs -d /scan -r > ${{ github.workspace }}/clamav-results.txt

      - name: Upload ClamAV scan results
        if: ${{ always() }}
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: clamav-results
          path: clamav-results.txt

      - name: Check ClamAV scan result
        run: |
          if grep -q "Infected files: 0" ${{ github.workspace }}/clamav-results.txt; then
            echo "No malware found."
          else
            echo "::warning::Malware detected!"
            cat ${{ github.workspace }}/clamav-results.txt
            exit 1
          fi

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@57a97c7e7821a5776cebc9bb87c984fa69cba8f1 # v0.35.0
        with:
          image-ref: ${{ steps.lower-repo.outputs.repository }}
          format: sarif
          output: trivy-results.sarif
          severity: CRITICAL,HIGH
          exit-code: 1
          ignore-unfixed: true

      - name: Upload Trivy scan results to GitHub Security tab
        if: always()
        uses: github/codeql-action/upload-sarif@65216971a11ded447a6b76263d5a144519e5eee1 # v2.25.2
        with:
          sarif_file: trivy-results.sarif
