name: Build infra-otc Docker Image on Push to GHCR

on:
  push:
    branches-ignore:
      #- main
      - DBP-2194-infra-otc-cert-manager-webhook-übergabefähig-machen
    #paths:
    #  - 'Dockerfile'

jobs:
  build_image_on_push:
    permissions:
      packages: write
      security-events: write
      actions: read
      contents: read
    uses: ./.github/workflows/build-push-ghcr.yaml
    with:
      image_name: "infra-otc-cert-manager-webhook"
      context: "./"
      file: "./Dockerfile"
