name: Build infra-otc on tag push

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build_image:
    permissions:
      packages: write
      contents: read
    uses: ./.github/workflows/build-push-ghcr.yaml
    with:
      image_name: infra-otc-cert-manager-webhook
      context: deploy/infra-otc-cert-manager-webhook/