name: "Publish image to GHCR and Helm chart to GH pages on tag"

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

concurrency:
  group: infra-otc-cert-manager-webhook-main
  cancel-in-progress: true

jobs:
  publish_docker:
    permissions:
      packages: write
      security-events: write
      contents: read
    uses: dBildungsplattform/dbp-github-workflows/.github/workflows/image-publish-trivy.yaml@7
    with:
      image_name: "infra-otc-cert-manager-webhook"
      run_trivy_scan: false
      run_clamav_scan: true
      image_tag_generation: "version_git_tag"
      add_latest_tag: true
      container_registry: "ghcr.io"
      limit-severities-for-sarif: false

  publish_helm:
    uses: dBildungsplattform/dbp-github-workflows/.github/workflows/chart-release.yaml@7
    secrets: inherit
    with:
      chart_path: deploy
      chart_name: infra-otc-cert-manager-webhook
      helm_chart_version_generation: specified
      image_tag_generation: specified
      helm_chart_version: ${{ github.ref_name }}
      image_tag: ${{ github.ref_name }}
