name: "Scan Helm on push"

on:
  push:

concurrency:
  group: infra-otc-cert-manager-webhook-scan-helm-${{ github.event.ref }}
  cancel-in-progress: true

jobs:
  scan_helm:
    uses: dBildungsplattform/dbp-github-workflows/.github/workflows/check-helm-kics.yaml@7
    permissions:
      contents: read
